# Generated by Django 6.0.1 on 2026-02-15 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
